# Análise das Compras e Contratações Públicas e Diferenças Regionais

### **Problema:**

Como as compras e contratações públicas se distribuem entre 
diferentes regiões do Brasil e quais temas aparecem com maior 
frequência nos objetos dessas contratações?

### **Objetivo:**

Analisar as diferenças regionais nas contratações públicas, 
comparando a quantidade e os valores das compras entre diferentes 
Unidades da Federação (UFs), além de identificar os principais 
temas presentes nas descrições dos objetos das contratações.

In [73]:
#%pip install requests pandas matplotlib -q

In [74]:
import requests
import pandas as pd
import matplotlib.pyplot as plt

In [75]:
BASE_URL = "https://dadosabertos.compras.gov.br"

ENDPOINT_CONTRATACOES = "/modulo-contratacoes/1_consultarContratacoes_PNCP_14133"


url = BASE_URL + ENDPOINT_CONTRATACOES

print(url)

https://dadosabertos.compras.gov.br/modulo-contratacoes/1_consultarContratacoes_PNCP_14133

In [76]:
params = {
    "pagina": 1,
    "tamanhoPagina": 10,
    "dataPublicacaoPncpInicial": "2026-01-01",
    "dataPublicacaoPncpFinal": "2026-06-30",
    "codigoModalidade": 5
}

params

{'pagina': 1,
 'tamanhoPagina': 10,
 'dataPublicacaoPncpInicial': '2026-01-01',
 'dataPublicacaoPncpFinal': '2026-06-30',
 'codigoModalidade': 5}

In [77]:
resposta = requests.get(
    url,
    params=params,
    timeout=60
)

print("Status HTTP:", resposta.status_code)
print("URL consultada:", resposta.url)

Status HTTP: 200
URL consultada: https://dadosabertos.compras.gov.br/modulo-contratacoes/1_consultarContratacoes_PNCP_14133?pagina=1&tamanhoPagina=10&dataPublicacaoPncpInicial=2026-01-01&dataPublicacaoPncpFinal=2026-06-30&codigoModalidade=5

In [78]:
dados = resposta.json()

In [79]:
def extrair_registros(json_resposta):
    if isinstance(json_resposta, list):
        return json_resposta

    if not isinstance(json_resposta, dict):
        return []

    for chave in ["resultado", "resultados", "data", "content"]:
        if chave in json_resposta and isinstance(json_resposta[chave], list):
            return json_resposta[chave]

    return []


registros = extrair_registros(dados)

print("Quantidade de registros encontrados:", len(registros))

Quantidade de registros encontrados: 10

In [80]:
df = pd.json_normalize(registros)

print("Dimensão:", df.shape)

df.head()

Dimensão: (10, 52)

,idCompra,numeroControlePNCP,anoCompraPncp,sequencialCompraPncp,orgaoEntidadeCnpj,orgaoSubrogadoCnpj,codigoOrgao,orgaoEntidadeRazaoSocial,orgaoSubrogadoRazaoSocial,orgaoEntidadeEsferaId,...,tipoInstrumentoConvocatorioNome,modoDisputaNomePncp,valorTotalEstimado,valorTotalHomologado,dataInclusaoPncp,dataAtualizacaoPncp,dataPublicacaoPncp,dataAberturaPropostaPncp,dataEncerramentoPropostaPncp,contratacaoExcluida
0,12063005900362025,00394429000100-1-003992/2025,2025,3992,00394429000100,None,43849,COMANDO DA AERONAUTICA,None,F,...,Edital,Aberto-Fechado,3421177.96,1746833.48,2026-01-02T07:00:04,2026-01-02T07:00:04,2026-01-02T07:00:04,2026-01-02T08:30:00,2026-01-16T10:00:00,False
1,75121205900142025,00394502000144-1-014558/2025,2025,14558,00394502000144,None,46041,COMANDO DA MARINHA,None,F,...,Edital,Aberto,16437160.40,6366941.80,2026-01-02T07:00:07,2026-01-02T07:00:07,2026-01-02T07:00:07,2026-01-02T08:00:00,2026-01-22T09:00:00,False
2,38932005900272025,47217146000157-1-000072/2025,2025,72,47217146000157,None,83451,CONSELHO FEDERAL DE ENFERMAGEM COFEN,None,F,...,Edital,Aberto,46778.20,46000.00,2026-01-02T07:00:10,2026-01-02T07:00:10,2026-01-02T07:00:10,2026-01-02T08:00:00,2026-01-16T09:00:00,False
3,38932005900262025,47217146000157-1-000073/2025,2025,73,47217146000157,None,83451,CONSELHO FEDERAL DE ENFERMAGEM COFEN,None,F,...,Edital,Aberto,1099821.97,970387.74,2026-01-02T07:00:12,2026-01-02T07:00:12,2026-01-02T07:00:12,2026-01-02T08:00:00,2026-01-16T09:00:00,False
4,15405105901052025,25944455000196-1-000193/2025,2025,193,25944455000196,None,75495,UNIVERSIDADE FEDERAL DE VICOSA,None,F,...,Edital,Aberto-Fechado,3214452.70,1927000.14,2026-01-02T07:00:14,2026-02-19T07:09:50,2026-01-02T07:00:14,2026-01-02T08:00:00,2026-03-05T09:00:00,False

In [81]:
for coluna in df.columns:
    print(coluna)

idCompra
numeroControlePNCP
anoCompraPncp
sequencialCompraPncp
orgaoEntidadeCnpj
orgaoSubrogadoCnpj
codigoOrgao
orgaoEntidadeRazaoSocial
orgaoSubrogadoRazaoSocial
orgaoEntidadeEsferaId
orgaoSubrogadoEsferaId
orgaoEntidadePoderId
orgaoSubrogadoPoderId
unidadeOrgaoCodigoUnidade
unidadeSubrogadaCodigoUnidade
unidadeOrgaoNomeUnidade
unidadeSubrogadaNomeUnidade
unidadeOrgaoUfSigla
unidadeSubrogadaUfSigla
unidadeOrgaoMunicipioNome
unidadeSubrogadaMunicipioNome
unidadeOrgaoCodigoIbge
unidadeSubrogadaCodigoIbge
numeroCompra
modalidadeIdPncp
codigoModalidade
modalidadeNome
srp
modoDisputaIdPncp
codigoModoDisputa
amparoLegalCodigoPncp
amparoLegalNome
amparoLegalDescricao
informacaoComplementar
processo
objetoCompra
existeResultado
orcamentoSigilosoCodigo
orcamentoSigilosoDescricao
situacaoCompraIdPncp
situacaoCompraNomePncp
tipoInstrumentoConvocatorioCodigoPncp
tipoInstrumentoConvocatorioNome
modoDisputaNomePncp
valorTotalEstimado
valorTotalHomologado
dataInclusaoPncp
dataAtualizacaoPncp
dataPublicacaoPncp
dataAberturaPropostaPncp
dataEncerramentoPropostaPncp
contratacaoExcluida

In [82]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 52 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   idCompra                               10 non-null     str
 1   numeroControlePNCP                     10 non-null     str
 2   anoCompraPncp                          10 non-null     int64
 3   sequencialCompraPncp                   10 non-null     int64
 4   orgaoEntidadeCnpj                      10 non-null     str
 5   orgaoSubrogadoCnpj                     0 non-null      object
 6   codigoOrgao                            10 non-null     int64
 7   orgaoEntidadeRazaoSocial               10 non-null     str
 8   orgaoSubrogadoRazaoSocial              0 non-null      object
 9   orgaoEntidadeEsferaId                  10 non-null     str
 10  orgaoSubrogadoEsferaId                 0 non-null      object
 11  orgaoEntidadePoderId                   10 non-null     str
 12  orgaoSubrogadoPoderId                  0 non-null      object
 13  unidadeOrgaoCodigoUnidade              10 non-null     str
 14  unidadeSubrogadaCodigoUnidade          0 non-null      object
 15  unidadeOrgaoNomeUnidade                10 non-null     str
 16  unidadeSubrogadaNomeUnidade            0 non-null      object
 17  unidadeOrgaoUfSigla                    10 non-null     str
 18  unidadeSubrogadaUfSigla                0 non-null      object
 19  unidadeOrgaoMunicipioNome              10 non-null     str
 20  unidadeSubrogadaMunicipioNome          0 non-null      object
 21  unidadeOrgaoCodigoIbge                 10 non-null     int64
 22  unidadeSubrogadaCodigoIbge             0 non-null      object
 23  numeroCompra                           10 non-null     str
 24  modalidadeIdPncp                       10 non-null     int64
 25  codigoModalidade                       10 non-null     int64
 26  modalidadeNome                         10 non-null     str
 27  srp                                    10 non-null     bool
 28  modoDisputaIdPncp                      10 non-null     int64
 29  codigoModoDisputa                      10 non-null     int64
 30  amparoLegalCodigoPncp                  10 non-null     int64
 31  amparoLegalNome                        10 non-null     str
 32  amparoLegalDescricao                   10 non-null     str
 33  informacaoComplementar                 10 non-null     str
 34  processo                               10 non-null     str
 35  objetoCompra                           10 non-null     str
 36  existeResultado                        10 non-null     bool
 37  orcamentoSigilosoCodigo                10 non-null     int64
 38  orcamentoSigilosoDescricao             10 non-null     str
 39  situacaoCompraIdPncp                   10 non-null     int64
 40  situacaoCompraNomePncp                 10 non-null     str
 41  tipoInstrumentoConvocatorioCodigoPncp  10 non-null     int64
 42  tipoInstrumentoConvocatorioNome        10 non-null     str
 43  modoDisputaNomePncp                    10 non-null     str
 44  valorTotalEstimado                     10 non-null     float64
 45  valorTotalHomologado                   10 non-null     float64
 46  dataInclusaoPncp                       10 non-null     str
 47  dataAtualizacaoPncp                    10 non-null     str
 48  dataPublicacaoPncp                     10 non-null     str
 49  dataAberturaPropostaPncp               10 non-null     str
 50  dataEncerramentoPropostaPncp           10 non-null     str
 51  contratacaoExcluida                    10 non-null     bool
dtypes: bool(3), float64(2), int64(12), object(9), str(26)
memory usage: 4.0+ KB

In [83]:
colunas_interesse = [
    "idCompra",
    "numeroControlePNCP",
    "numeroCompra",
    "anoCompra",
    "modalidadeNome",
    "modalidadeIdPncp",
    "unidadeOrgao.ufSigla",
    "unidadeOrgao.municipioNome",
    "unidadeOrgao.codigoIbge",
    "unidadeOrgao.nomeUnidade",
    "unidadeOrgao.codigoUnidade",
    "orgaoEntidade.razaoSocial",
    "orgaoEntidade.cnpj",
    "orgaoEntidade.esferaId",
    "orgaoEntidade.poderId",
    "objetoCompra",
    "valorTotalEstimado",
    "valorTotalHomologado",
    "dataPublicacaoPncp",
    "srp"
]

colunas_existentes = [c for c in colunas_interesse if c in df.columns]

print("Colunas encontradas:")
print(colunas_existentes)

df[colunas_existentes].head() if colunas_existentes else df.head()

Colunas encontradas:
['idCompra', 'numeroControlePNCP', 'numeroCompra', 'modalidadeNome', 'modalidadeIdPncp', 'objetoCompra', 'valorTotalEstimado', 'valorTotalHomologado', 'dataPublicacaoPncp', 'srp']

,idCompra,numeroControlePNCP,numeroCompra,modalidadeNome,modalidadeIdPncp,objetoCompra,valorTotalEstimado,valorTotalHomologado,dataPublicacaoPncp,srp
0,12063005900362025,00394429000100-1-003992/2025,90036,Pregão - Eletrônico,6,Contratacao de empresa(s) especializada(s) na ...,3421177.96,1746833.48,2026-01-02T07:00:04,True
1,75121205900142025,00394502000144-1-014558/2025,90014,Pregão - Eletrônico,6,Contratação de empresa especializada para pres...,16437160.40,6366941.80,2026-01-02T07:00:07,True
2,38932005900272025,47217146000157-1-000072/2025,90027,Pregão - Eletrônico,6,Contratação de serviços contínuos de seguro im...,46778.20,46000.00,2026-01-02T07:00:10,False
3,38932005900262025,47217146000157-1-000073/2025,90026,Pregão - Eletrônico,6,"Aquisição de mobiliário, via registro de preço...",1099821.97,970387.74,2026-01-02T07:00:12,True
4,15405105901052025,25944455000196-1-000193/2025,90105,Pregão - Eletrônico,6,"Aquisição e instalação de elevadores, com cont...",3214452.70,1927000.14,2026-01-02T07:00:14,False

In [93]:
def consultar_contratacoes_uf(uf, tamanho=500):

    parametros = {
        "pagina": 1,
        "tamanhoPagina": tamanho,
        "dataPublicacaoPncpInicial": "2026-01-01",
        "dataPublicacaoPncpFinal": "2026-06-30",
        "codigoModalidade": 5,
        "unidadeOrgaoUfSigla": uf
    }

    r = requests.get(
        url,
        params=parametros,
        timeout=60
    )

    r.raise_for_status()

    registros = extrair_registros(r.json())

    return pd.json_normalize(registros)

In [95]:
df_sp = consultar_contratacoes_uf("SP")
df_rj = consultar_contratacoes_uf("RJ")
df_mg = consultar_contratacoes_uf("MG")
df_pr = consultar_contratacoes_uf("PR")

df = pd.concat(
    [df_sp, df_rj, df_mg, df_pr],
    ignore_index=True
)

print("Total de registros:", len(df))

Total de registros: 2000

In [96]:
def coletar_paginas(endpoint, parametros, numero_paginas=10):

    todos = []

    for pagina in range(1, numero_paginas + 1):

        params_pagina = parametros.copy()
        params_pagina["pagina"] = pagina

        resposta = requests.get(
            BASE_URL + endpoint,
            params=params_pagina,
            timeout=60
        )

        resposta.raise_for_status()

        registros = extrair_registros(resposta.json())

        print(f"Página {pagina}: {len(registros)} registros")

        if len(registros) == 0:
            break

        todos.extend(registros)

    return pd.json_normalize(todos)

In [98]:
params_coleta = {

    "tamanhoPagina": 500,

    "dataPublicacaoPncpInicial": "2026-01-01",

    "dataPublicacaoPncpFinal": "2026-06-30",

    "codigoModalidade": 5,

    "unidadeOrgaoUfSigla": "SP"

}

df_coleta = coletar_paginas(

    ENDPOINT_CONTRATACOES,

    params_coleta,

    numero_paginas=10

)

print("Dimensão final:", df_coleta.shape)

df_coleta.head()

Página 1: 500 registros
Página 2: 500 registros
Página 3: 500 registros
Página 4: 500 registros
Página 5: 500 registros
Página 6: 500 registros
Página 7: 500 registros
Página 8: 500 registros
Página 9: 500 registros
Página 10: 500 registros
Dimensão final: (5000, 52)

,idCompra,numeroControlePNCP,anoCompraPncp,sequencialCompraPncp,orgaoEntidadeCnpj,orgaoSubrogadoCnpj,codigoOrgao,orgaoEntidadeRazaoSocial,orgaoSubrogadoRazaoSocial,orgaoEntidadeEsferaId,...,tipoInstrumentoConvocatorioNome,modoDisputaNomePncp,valorTotalEstimado,valorTotalHomologado,dataInclusaoPncp,dataAtualizacaoPncp,dataPublicacaoPncp,dataAberturaPropostaPncp,dataEncerramentoPropostaPncp,contratacaoExcluida
0,92500305912802025,13864377000130-1-002228/2025,2025,2228,13864377000130,NaN,65479,FUNDO MUNICIPAL DE SAUDE - FMS,NaN,M,...,Edital,Aberto-Fechado,7642010.7,5614486.800,2026-01-02T07:00:49,2026-01-02T07:00:49,2026-01-02T07:00:49,2026-01-02T08:00:00,2026-01-16T09:00:00,False
1,08032105900042025,46384111000140-1-001967/2025,2025,1967,46384111000140,NaN,35411,SAO PAULO SECRETARIA DA EDUCACAO,NaN,E,...,Edital,Aberto,1073607.0,1036000.000,2026-01-02T07:00:58,2026-01-02T07:00:58,2026-01-02T07:00:58,2026-01-02T08:00:00,2026-01-16T09:00:00,False
2,92500305912832025,13864377000130-1-002229/2025,2025,2229,13864377000130,NaN,65479,FUNDO MUNICIPAL DE SAUDE - FMS,NaN,M,...,Edital,Aberto-Fechado,5121000.0,5004000.000,2026-01-02T07:01:04,2026-01-02T07:01:04,2026-01-02T07:01:04,2026-01-02T08:00:00,2026-01-14T09:00:00,False
3,09011705901162025,46374500000194-1-012814/2025,2025,12814,46374500000194,NaN,34952,SECRETARIA DE ESTADO DA SAUDE,NaN,E,...,Edital,Aberto-Fechado,0.0,NaN,2026-01-02T07:01:05,2026-01-02T07:01:05,2026-01-02T07:01:05,2026-01-02T08:00:00,2026-02-02T08:00:00,False
4,09018305903432025,46374500000194-1-012815/2025,2025,12815,46374500000194,NaN,34952,SECRETARIA DE ESTADO DA SAUDE,NaN,E,...,Edital,Aberto,125133.0,60772.875,2026-01-02T07:01:10,2026-01-02T07:01:10,2026-01-02T07:01:10,2026-01-02T08:00:00,2026-01-15T08:00:00,False

In [99]:
print("Linhas duplicadas completas:", df_coleta.duplicated().sum())

if "idCompra" in df_coleta.columns:
    print("IDs de compra duplicados:", df_coleta["idCompra"].duplicated().sum())

Linhas duplicadas completas: 0
IDs de compra duplicados: 0

In [101]:
percentual_ausentes = (
    df_coleta.isna()
    .mean()
    .mul(100)
    .sort_values(ascending=False)
    .round(2)
)

percentual_ausentes = percentual_ausentes[
    percentual_ausentes > 0
]

print("Colunas com valores ausentes:")
print(percentual_ausentes)

Colunas com valores ausentes:
orgaoSubrogadoPoderId            99.98
orgaoSubrogadoEsferaId           99.98
orgaoSubrogadoRazaoSocial        99.98
orgaoSubrogadoCnpj               99.98
unidadeSubrogadaNomeUnidade      99.98
unidadeSubrogadaUfSigla          99.98
unidadeSubrogadaCodigoUnidade    99.98
unidadeSubrogadaMunicipioNome    99.98
unidadeSubrogadaCodigoIbge       99.98
valorTotalHomologado             16.08
dtype: float64